#!/bin/bash
#SBATCH -p v3_64
#SBATCH -N 1
#SBATCH -n 24
source /public1/soft/other/vasp/cn-module-vasp.5.4.4.sh
module  unload intel/17.0.7
module load  mpi/intel/5.0.3.049
module load vasp/intel-17/vasp544
module load QE


PSEUDO_DIR='/public1/home/sc30830/pseudo/precision_pseudos/'
diago='david'

#scf-nscf-(dos-bands)
cat > si.scf.in << eof
&control
        calculation='scf'
        restart_mode='from_scratch'
        prefix='silicon'
        tstress=.true.
        tprnfor=.true.
        pseudo_dir='$PSEUDO_DIR'
        outdir='./outdir'
/
&system
        ibrav=2
        celldm(1)=10.2
        nat=2
        ntyp=1
        ecutwfc=18.0
/
&electrons
        diagonalization='$diago'
!        mixing_mode='plain'
!        mixing_beta=0.7
        conv_thr=1.0e-8
/
ATOMIC_SPECIES
  Si 28.086 Si.pbe-n-rrkjus_psl.1.0.0.UPF
ATOMIC_POSITIONS (alat)
Si 0.00 0.00 0.00
Si 0.25 0.25 0.25
K_POINTS (automatic)
    8 8 8 0 0 0
eof
srun pw.x < si.scf.in > si.scf.out

cat > si.nscf.in << eof
&control
        calculation='nscf'
        restart_mode='from_scratch'
        prefix='silicon'
        pseudo_dir='/public1/home/sc30830/pseudo/precision_pseudos/'
        outdir='./outdir'
/
&system
        ibrav=2
        celldm(1)=10.2
        nat=2
        ntyp=1
        ecutwfc=18.0
        nbnd = 8
        occupations='tetrahedra'
        ! occupations='smearing', smearing='gaussian', degauss=0.005
/
&electrons
        diagonalization='david'
        conv_thr=1.0e-8
/
ATOMIC_SPECIES
  Si 28.086 Si.pbe-n-rrkjus_psl.1.0.0.UPF

ATOMIC_POSITIONS (alat)
Si 0.00 0.00 0.00
Si 0.25 0.25 0.25
K_POINTS  (automatic)
  12 12 12 0 0 0
eof
srun pw.x < si.nscf.in > si.nscf.out

cat > si.bands.in << eof
&control
        calculation='bands'
        restart_mode='from_scratch'
        prefix='silicon'
        pseudo_dir='/public1/home/sc30830/pseudo/precision_pseudos/'
        outdir='./outdir'
/
&system
        ibrav=2
        celldm(1)=10.2
        nat=2
        ntyp=1
        ecutwfc=18.0
        nbnd = 8
/
&electrons
        diagonalization='david'
        conv_thr=1.0e-8
/
ATOMIC_SPECIES
  Si 28.086 Si.pbe-n-rrkjus_psl.1.0.0.UPF

ATOMIC_POSITIONS (alat)
Si 0.00 0.00 0.00
Si 0.25 0.25 0.25

K_POINTS {crystal_b}
5
  0.0000 0.5000 0.0000 20 !L
  0.0000 0.0000 0.0000 30 !Gamma
  -0.500 0.0000 -0.500 10 !X
  -0.375 0.2500 -0.375 30 !U
  0.0000 0.0000 0.0000 20 !Gamma
eof
srun pw.x < si.bands.in > si.bands.out

# Use the dos.x to calculate the dos
cat > si.dos.in << eof
&DOS
        prefix='silicon'
        outdir='./outdir'
        Emin=-9.0
        Emax=16.0
        fildos='si.dos.dat'
/
eof
srun dos.x < si.dos.in > si.dos.out

# Post processing
cat > si.bands.pp.in << eof
&bands
        outdir='./outdir/'
        prefix='silicon'
        filband='si.bands.dat'
/
eof
srun bands.x < si.bands.pp.in > si.bands.pp.out


