#!/bin/bash
#SBATCH -p v3_64
#SBATCH -N 1
#SBATCH -n 24
source /public1/soft/other/vasp/cn-module-vasp.5.4.4.sh
module  unload intel/17.0.7
module load  mpi/intel/5.0.3.049
module load vasp/intel-17/vasp544
module load QE

PSEUDO_DIR='/public1/home/sc30830/pseudo/precision_pseudos/'
cat > si.scf.in << EOF
 &control
    calculation='scf',
    restart_mode='from_scratch',
    prefix='silicon'
    pseudo_dir = '$PSEUDO_DIR/',
    outdir='./outdir/'
 /
 &system
    ibrav = 2, celldm(1) =10.20, nat=  2, ntyp= 1,
    ecutwfc = 18.0
 /
 &electrons
    mixing_beta = 0.7
    conv_thr =  1.0d-8
 /
ATOMIC_SPECIES
 Si  28.086  Si.pbe-n-rrkjus_psl.1.0.0.UPF
ATOMIC_POSITIONS (alat)
 Si 0.00 0.00 0.00
 Si 0.25 0.25 0.25
K_POINTS (automatic)
  8 8 8 0 0 0 
EOF
srun pw.x < si.scf.in >si.scf.out

cat > si.phG.in << EOF
phonons of Si at Gamma
 &inputph
  tr2_ph=1.0d-14,
  prefix='silicon',
  epsil=.true.,
  amass(1)=28.08,
  outdir='./outdir',
  fildyn='si.dynG',
 /
0.0 0.0 0.0
EOF
srun  ph.x < si.phG.in > si.phG.out
